version: '3'
services:
  django:
    container_name: docker-django
    build: ./tsp
    volumes:
      - ./tsp:/project
    ports:
      - 8081:8000
    depends_on: 
      - db

  nginx:
    container_name: docker-nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tsp/media:/usr/share/nginx/media
      - ./tsp/static:/usr/share/nginx/static
    ports:
      - "80:8080"
    depends_on:
      - django


  db:
    container_name: docker-db
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7620
      MYSQL_DATABASE: stp
    ports:
      - 3302:3306
volumes:
  mysql_data:
  
