version: '3'
services:
  db:
    container_name: docker-local-mysql
    image: mysql:5.7
    volumes:
      - "../mysql_data:/var/lib/mysql"
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 7620
      MYSQL_DATABASE: stp

  django:
    container_name: docker-django
    build: ./tsp
    volumes:
      - ./tsp:/project
    ports:
      - 8081:8000
    depends_on:
      - db

  nginx:
    container_name: docker-nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tsp/media:/usr/share/nginx/media
      - ./tsp/static:/usr/share/nginx/static
    ports:
      - "8006:8080"
    depends_on:
      - django



  
