version: '3'
services:
  django:
    container_name: docker-django
    build: ./tsp
    volumes:
      - ./tsp:/project
    ports:
      - 8081:8000

  nginx:
    container_name: docker-nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./tsp/media:/usr/share/nginx/media
      - ./tsp/static:/usr/share/nginx/static
      - ./tsp/info.log:/var/log/digdaklog.log
    ports:
      - "80:8080"
    depends_on:
      - django



  
