# Generated by Django 2.2.7 on 2019-11-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('sta_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transit_slip.Sta')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltr_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('u_string', models.CharField(max_length=5)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_unit', to='transit_slip.Unit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_unit', to='transit_slip.Unit')),
            ],
            options={
                'unique_together': {('date', 'u_string')},
            },
        ),
    ]
