# Generated by Django 2.2.7 on 2019-11-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0002_letter_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='letter',
            name='qr_image_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
