# Generated by Django 2.2.7 on 2019-11-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transit_slip.Unit'),
        ),
    ]
