# Generated by Django 2.2.7 on 2019-11-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0005_auto_20191118_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='to_unit',
        ),
        migrations.AddField(
            model_name='letter',
            name='to_unit',
            field=models.ManyToManyField(related_name='to_unit', to='transit_slip.Unit'),
        ),
    ]
