# Generated by Django 2.2.7 on 2019-11-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0006_auto_20191126_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='to_unit',
            field=models.ManyToManyField(blank=True, related_name='to_unit', to='transit_slip.Unit'),
        ),
    ]
