# Generated by Django 2.2.7 on 2019-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0007_auto_20191127_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='to_unit',
            field=models.ManyToManyField(blank=True, null=True, related_name='to_unit', to='transit_slip.Unit'),
        ),
    ]
