# Generated by Django 2.2.7 on 2019-11-28 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0009_auto_20191128_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
