# Generated by Django 2.2.7 on 2019-11-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0010_letter_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='qr_image',
            field=models.FileField(blank=True, upload_to='qr_code_test/'),
        ),
    ]
