# Generated by Django 2.2.7 on 2019-11-28 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0011_letter_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='qr_image',
        ),
    ]
