# Generated by Django 2.2.7 on 2019-11-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0012_remove_letter_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='to_unit',
        ),
        migrations.AddField(
            model_name='letter',
            name='to_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='to_unit', to='transit_slip.Unit'),
            preserve_default=False,
        ),
    ]
