# Generated by Django 2.2.7 on 2019-11-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0014_auto_20191130_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='spl_pkg',
            field=models.BooleanField(default=False),
        ),
    ]
