# Generated by Django 2.2.7 on 2019-12-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0015_letter_spl_pkg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='received_at_sigcen',
            field=models.DateField(null=True),
        ),
    ]
