# Generated by Django 2.2.7 on 2019-12-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0017_auto_20191210_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='received_at_sigcen',
            field=models.DateTimeField(null=True),
        ),
    ]
