# Generated by Django 2.2.7 on 2019-12-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0018_auto_20191210_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='despatched_at',
            field=models.DateTimeField(null=True),
        ),
    ]
