# Generated by Django 2.2.7 on 2019-12-13 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transit_slip', '0019_letter_despatched_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrsnsitSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('ltr_ids', models.TextField(blank=True, null=True)),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transit_slip.Sta')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
