# Generated by Django 2.2.7 on 2019-12-15 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transit_slip', '0020_trsnsitslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('dst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transit_slip.Sta')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TrsnsitSlip',
        ),
        migrations.AddField(
            model_name='letter',
            name='transit_slip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit_slip.TransitSlip'),
        ),
    ]
