# Generated by Django 2.2.7 on 2019-12-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0023_auto_20191220_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitslip',
            name='received_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('sc', 'Sigcen clk'), ('ad', 'Admin'), ('uc', 'Unit clk')], default='uc', max_length=2, null=True),
        ),
    ]
