# Generated by Django 2.2.7 on 2019-12-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0025_auto_20191226_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('sc', 'Sigcen clk'), ('uc', 'Unit clk'), ('ad', 'Admin')], default='uc', max_length=2, null=True),
        ),
    ]
