# Generated by Django 2.2.7 on 2020-02-01 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transit_slip', '0026_auto_20191227_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('sc', 'Sigcen clk'), ('ad', 'Admin'), ('uc', 'Unit clk')], default='uc', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='LetterReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_dt', models.DateTimeField()),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transit_slip.Unit')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='letter',
            name='ltr_receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit_slip.LetterReceipt'),
        ),
    ]
