# Generated by Django 2.2.7 on 2020-02-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0028_auto_20200201_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='despatched_at',
        ),
        migrations.AddField(
            model_name='letter',
            name='classification',
            field=models.CharField(choices=[('uc', 'Unclass'), ('ts', 'Top Secret'), ('cf', 'Confidential'), ('sc', 'Secret'), ('rs', 'Restricted')], default='rs', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('sc', 'Sigcen clk'), ('uc', 'Unit clk'), ('ad', 'Admin')], default='uc', max_length=2, null=True),
        ),
    ]
