# Generated by Django 2.2.7 on 2020-02-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0029_auto_20200228_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('ts', 'Top Secret'), ('cf', 'Confidential'), ('rs', 'Restricted'), ('sc', 'Secret'), ('uc', 'Unclass')], default='rs', max_length=2, null=True),
        ),
    ]
