# Generated by Django 2.2.7 on 2020-02-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0030_auto_20200228_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='addr_line_2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('rs', 'Restricted'), ('ts', 'Top Secret'), ('sc', 'Secret'), ('uc', 'Unclass'), ('cf', 'Confidential')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('uc', 'Unit clk'), ('ad', 'Admin'), ('sc', 'Sigcen clk')], default='uc', max_length=2, null=True),
        ),
    ]
