# Generated by Django 2.2.7 on 2020-02-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0031_auto_20200228_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='sta',
            name='sta_full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('rs', 'Restricted'), ('sc', 'Secret'), ('ts', 'Top Secret'), ('cf', 'Confidential'), ('uc', 'Unclass')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ad', 'Admin'), ('uc', 'Unit clk'), ('sc', 'Sigcen clk')], default='uc', max_length=2, null=True),
        ),
    ]
