# Generated by Django 2.2.7 on 2020-02-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0032_auto_20200228_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='letter_type',
            field=models.CharField(default='reg', max_length=3),
        ),
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('ts', 'Top Secret'), ('sc', 'Secret'), ('cf', 'Confidential'), ('uc', 'Unclass'), ('rs', 'Restricted')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('uc', 'Unit clk'), ('sc', 'Sigcen clk'), ('ad', 'Admin')], default='uc', max_length=2, null=True),
        ),
    ]
