# Generated by Django 2.2.7 on 2020-02-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0033_auto_20200228_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='addr_line_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('ts', 'Top Secret'), ('rs', 'Restricted'), ('sc', 'Secret'), ('uc', 'Unclass'), ('cf', 'Confidential')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ad', 'Admin'), ('sc', 'Sigcen clk'), ('uc', 'Unit clk')], default='uc', max_length=2, null=True),
        ),
    ]
