# Generated by Django 2.2.7 on 2020-02-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0035_auto_20200229_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='addr_line_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('cf', 'Confidential'), ('rs', 'Restricted'), ('sc', 'Secret'), ('uc', 'Unclass'), ('ts', 'Top Secret')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('uc', 'Unit clk'), ('ad', 'Admin'), ('sc', 'Sigcen clk')], default='uc', max_length=2, null=True),
        ),
    ]
