# Generated by Django 2.2.7 on 2020-02-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0036_auto_20200229_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('rs', 'Restricted'), ('uc', 'Unclass'), ('sc', 'Secret'), ('ts', 'Top Secret'), ('cf', 'Confidential')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ad', 'Admin'), ('uc', 'Unit clk'), ('sc', 'Sigcen clk')], default='uc', max_length=2, null=True),
        ),
    ]
