# Generated by Django 2.2.7 on 2020-03-21 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transit_slip', '0038_auto_20200320_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(null=True)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('uc', 'Unclass'), ('rs', 'Restricted'), ('sc', 'Secret'), ('ts', 'Top Secret'), ('cf', 'Confidential')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ad', 'Admin'), ('sc', 'Sigcen clk'), ('uc', 'Unit clk')], default='uc', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='OutGoingLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=5)),
                ('ltr_no', models.CharField(max_length=50)),
                ('ts_info', models.CharField(max_length=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ltrs', to='transit_slip.DeliveryReceipt')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orig_unit', to='transit_slip.Unit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dst_unit', to='transit_slip.Unit')),
            ],
        ),
    ]
