# Generated by Django 2.2.7 on 2020-03-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0039_auto_20200321_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryreceipt',
            old_name='received_by',
            new_name='recepient_name',
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='recepient_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryreceipt',
            name='recepient_rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('uc', 'Unclass'), ('rs', 'Restricted'), ('cf', 'Confidential'), ('sc', 'Secret'), ('ts', 'Top Secret')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('sc', 'Sigcen clk'), ('uc', 'Unit clk'), ('ad', 'Admin')], default='uc', max_length=2, null=True),
        ),
    ]
