# Generated by Django 2.2.7 on 2020-03-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0040_auto_20200321_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('cf', 'Confidential'), ('rs', 'Restricted'), ('ts', 'Top Secret'), ('sc', 'Secret'), ('uc', 'Unclass')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ad', 'Admin'), ('uc', 'Unit clk'), ('sc', 'Sigcen clk')], default='uc', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transitslip',
            name='received_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
