# Generated by Django 2.2.7 on 2020-04-07 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0041_auto_20200322_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('rs', 'Restricted'), ('uc', 'Unclass'), ('sc', 'Secret'), ('ts', 'Top Secret'), ('cf', 'Confidential')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingletter',
            name='delivery_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ltrs', to='transit_slip.DeliveryReceipt'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='outgoingletter',
            unique_together={('date', 'code')},
        ),
    ]
