# Generated by Django 2.2.7 on 2020-04-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0043_auto_20200424_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='through_sigcen',
        ),
        migrations.AddField(
            model_name='transitslip',
            name='through_sigcens',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('uc', 'Unclass'), ('cf', 'Confidential'), ('ts', 'Top Secret'), ('rs', 'Restricted'), ('sc', 'Secret')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit_slip.Unit'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('sc', 'Sigcen clk'), ('ad', 'Admin'), ('uc', 'Unit clk')], default='uc', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transitslip',
            name='dst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit_slip.Sta'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='sta_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit_slip.Sta'),
        ),
    ]
