# Generated by Django 2.2.7 on 2020-04-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0044_auto_20200424_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('sc', 'Secret'), ('cf', 'Confidential'), ('rs', 'Restricted'), ('ts', 'Top Secret'), ('uc', 'Unclass')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('uc', 'Unit clk'), ('sc', 'Sigcen clk'), ('ad', 'Admin')], default='uc', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transitslip',
            name='through_sigcens',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
