# Generated by Django 2.2.7 on 2020-04-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0045_auto_20200425_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('uc', 'Unclass'), ('cf', 'Confidential'), ('sc', 'Secret'), ('ts', 'Top Secret'), ('rs', 'Restricted')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('ad', 'Admin'), ('uc', 'Unit clk'), ('sc', 'Sigcen clk')], default='uc', max_length=2, null=True),
        ),
    ]
