# Generated by Django 2.2.7 on 2020-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0047_auto_20200428_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('sc', 'Secret'), ('cf', 'Confidential'), ('ts', 'Top Secret'), ('rs', 'Restricted'), ('uc', 'Unclass')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('sc', 'Sigcen clk'), ('ad', 'Admin'), ('uc', 'Unit clk')], default='uc', max_length=2, null=True),
        ),
    ]
