# Generated by Django 2.2.7 on 2020-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0048_auto_20200429_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('rs', 'Restricted'), ('cf', 'Confidential'), ('sc', 'Secret'), ('ts', 'Top Secret'), ('uc', 'Unclass')], default='rs', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('uc', 'Unit clk'), ('ad', 'Admin'), ('sc', 'Sigcen clk')], default='uc', max_length=2, null=True),
        ),
    ]
