# Generated by Django 2.2.7 on 2020-04-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0049_auto_20200429_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit_slip.Unit'),
        ),
    ]
