# Generated by Django 2.2.7 on 2020-04-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0050_unit_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='delivered_locally',
            field=models.BooleanField(default=False),
        ),
    ]
