# Generated by Django 2.2.7 on 2020-05-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0051_letter_delivered_locally'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='rtu_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transit_slip.Letter'),
        ),
    ]
