# Generated by Django 2.2.7 on 2020-05-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_slip', '0052_letter_rtu_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_stas',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='classification',
            field=models.CharField(blank=True, choices=[('rs', 'RESTRICTED'), ('cf', 'CONFIDENTIAL'), ('sc', 'SECRET'), ('ts', 'TOP SECRET'), ('uc', 'UNCLASS')], default='rs', max_length=2, null=True),
        ),
    ]
